development:
  dialect: "mysql"
  database: "kidlogger.net"
  host: "192.168.45.17"
  port: "3306"
  user: "developer"
  password: "deonex.com"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(localhost:3306)/recipes_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/recipes_production?parseTime=true&multiStatements=true&readTimeout=1s"}}